# Generated by Django 4.2.4 on 2024-10-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_isp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroincidente',
            name='titulo',
            field=models.CharField(choices=[('Preconceito de Raça ou de Cor', 'Preconceito de Raça ou de Cor'), ('Injúria por preconceito', 'Injúria por preconceito')], max_length=255),
        ),
    ]
