# Generated by Django 4.2.4 on 2024-10-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_isp', '0002_alter_registroincidente_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroincidente',
            name='cor',
            field=models.CharField(choices=[('Negra', 'Negra'), ('Parda', 'Parda'), ('Amarela', 'Amarela'), ('Indígena', 'Indígena'), ('Não informada', 'Não informada')], max_length=50),
        ),
    ]
